In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [16]:
url = "https://raw.githubusercontent.com/wuzhong-zhu/fp/main/foodpanda_data.csv"

# Assign colum names to the dataset
names = ['cuisine', 'orderCnt', 'customerID']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url)

In [17]:
dataset

cuisine  Numbers of order  Customer_id
0               Fast Food                10            1
1          Cakes & Bakery                 2            1
2                 Western                 1            1
3    Non-alcoholic Drinks                 1            1
4                 Chinese                 4            1
..                    ...               ...          ...
934           Singaporean                 4          100
935               Chicken                 2          100
936                Indian                 3          100
937            Sandwiches                 2          100
938               Burgers                 1          100

[939 rows x 3 columns]

In [107]:
cols = dataset["cuisine"].unique()
IDs = dataset["Customer_id"].unique()

cols = np.insert(cols,0,["customerID"])
df = pd.DataFrame(columns=cols)

for i in IDs:
    df = df.append({"customerID": i}, ignore_index=True)

for index, row in dataset.iterrows():
    df.loc[df.customerID == row['Customer_id'],row['cuisine']] = row['Numbers of order']

df

['customerID' 'Fast Food' 'Cakes & Bakery' 'Western'
 'Non-alcoholic Drinks' 'Chinese' 'Pizza' 'Thai' 'Indian' 'American'
 'Vietnamese' 'Singaporean' 'Desserts' 'Japanese' 'Burgers' 'Malaysian'
 'Halal' 'Italian' 'Healthy Food' 'European' 'Chicken' 'Korean'
 'Melaka Portuguese' 'Asian' 'Mexican' 'Sandwiches' 'Indonesian'
 'International' 'French' 'Seafood' 'Middle Eastern' 'Malay' 'Vegetarian'
 'Filipino' 'Turkish' 'German' 'Sushi' 'Mediterranean']


customerID  Fast Food  Cakes & Bakery  Western  Non-alcoholic Drinks  \
0          1.0       10.0             2.0      1.0                   1.0   
1          2.0        2.0             NaN      4.0                   NaN   
2          3.0        NaN             2.0      2.0                   NaN   
3          4.0        3.0             1.0      1.0                   5.0   
4          5.0        2.0             NaN      9.0                   2.0   
..         ...        ...             ...      ...                   ...   
95        96.0        7.0             NaN      NaN                   NaN   
96        97.0        NaN             NaN      8.0                   NaN   
97        98.0        2.0             NaN      2.0                   1.0   
98        99.0        6.0             1.0      2.0                   1.0   
99       100.0        5.0             NaN      NaN                   NaN   

    Chinese  Pizza  Thai  Indian  American  ...  French  Seafood  \
0       4.0    5.0   1.0     1.0       2.0  ...     NaN      NaN   
1      11.0    2.0   NaN     NaN       6.0  ...     NaN      NaN   
2       6.0    NaN   2.0     1.0       1.0  ...     NaN      NaN   
3       6.0    NaN   1.0     NaN       2.0  ...     NaN      NaN   
4       4.0    NaN   NaN    10.0       4.0  ...     NaN      NaN   
..      ...    ...   ...     ...       ...  ...     ...      ...   
95     25.0    NaN   NaN     NaN       2.0  ...     NaN      NaN   
96      6.0    1.0   NaN     NaN       1.0  ...     NaN      NaN   
97     12.0    2.0   NaN     NaN       NaN  ...     NaN      NaN   
98     13.0    3.0   NaN     NaN       NaN  ...     NaN      NaN   
99     18.0    NaN   NaN     3.0       NaN  ...     NaN      NaN   

    Middle Eastern  Malay  Vegetarian  Filipino  Turkish  German  Sushi  \
0              NaN    NaN         NaN       NaN      NaN     NaN    NaN   
1              NaN    NaN         NaN       NaN      NaN     NaN    NaN   
2              NaN    NaN         NaN       NaN      NaN     NaN    NaN   
3              NaN    NaN         NaN       NaN      NaN     NaN    NaN   
4              NaN    NaN         NaN       NaN      NaN     NaN    NaN   
..             ...    ...         ...       ...      ...     ...    ...   
95             NaN    NaN         NaN       NaN      7.0     NaN    NaN   
96             NaN    NaN         NaN       NaN      NaN     NaN    NaN   
97             NaN    NaN         NaN       NaN      NaN     NaN    NaN   
98             NaN    NaN         NaN       NaN      NaN     NaN    NaN   
99             NaN    NaN         NaN       NaN      NaN     NaN    NaN   

    Mediterranean  
0             NaN  
1             NaN  
2             NaN  
3             NaN  
4             NaN  
..            ...  
95            NaN  
96            NaN  
97            NaN  
98            NaN  
99            NaN  

[100 rows x 38 columns]

In [125]:
cols = dataset["cuisine"].unique()
cols = np.insert(cols, 0, ["result"])
cols = np.insert(cols, 0, ["customerID"])
df2 = pd.DataFrame(columns=cols)

for index, row in dataset.iterrows():
    for i in range(row['Numbers of order']):
        df2 = df2.append({
            "result":row['cuisine'],
            "customerID":row["Customer_id"]}, ignore_index=True)

df2

customerID      result Fast Food Cakes & Bakery Western  \
0             1   Fast Food       NaN            NaN     NaN   
1             1   Fast Food       NaN            NaN     NaN   
2             1   Fast Food       NaN            NaN     NaN   
3             1   Fast Food       NaN            NaN     NaN   
4             1   Fast Food       NaN            NaN     NaN   
...         ...         ...       ...            ...     ...   
3905        100      Indian       NaN            NaN     NaN   
3906        100      Indian       NaN            NaN     NaN   
3907        100  Sandwiches       NaN            NaN     NaN   
3908        100  Sandwiches       NaN            NaN     NaN   
3909        100     Burgers       NaN            NaN     NaN   

     Non-alcoholic Drinks Chinese Pizza Thai Indian  ... French Seafood  \
0                     NaN     NaN   NaN  NaN    NaN  ...    NaN     NaN   
1                     NaN     NaN   NaN  NaN    NaN  ...    NaN     NaN   
2                     NaN     NaN   NaN  NaN    NaN  ...    NaN     NaN   
3                     NaN     NaN   NaN  NaN    NaN  ...    NaN     NaN   
4                     NaN     NaN   NaN  NaN    NaN  ...    NaN     NaN   
...                   ...     ...   ...  ...    ...  ...    ...     ...   
3905                  NaN     NaN   NaN  NaN    NaN  ...    NaN     NaN   
3906                  NaN     NaN   NaN  NaN    NaN  ...    NaN     NaN   
3907                  NaN     NaN   NaN  NaN    NaN  ...    NaN     NaN   
3908                  NaN     NaN   NaN  NaN    NaN  ...    NaN     NaN   
3909                  NaN     NaN   NaN  NaN    NaN  ...    NaN     NaN   

     Middle Eastern Malay Vegetarian Filipino Turkish German Sushi  \
0               NaN   NaN        NaN      NaN     NaN    NaN   NaN   
1               NaN   NaN        NaN      NaN     NaN    NaN   NaN   
2               NaN   NaN        NaN      NaN     NaN    NaN   NaN   
3               NaN   NaN        NaN      NaN     NaN    NaN   NaN   
4               NaN   NaN        NaN      NaN     NaN    NaN   NaN   
...             ...   ...        ...      ...     ...    ...   ...   
3905            NaN   NaN        NaN      NaN     NaN    NaN   NaN   
3906            NaN   NaN        NaN      NaN     NaN    NaN   NaN   
3907            NaN   NaN        NaN      NaN     NaN    NaN   NaN   
3908            NaN   NaN        NaN      NaN     NaN    NaN   NaN   
3909            NaN   NaN        NaN      NaN     NaN    NaN   NaN   

     Mediterranean  
0              NaN  
1              NaN  
2              NaN  
3              NaN  
4              NaN  
...            ...  
3905           NaN  
3906           NaN  
3907           NaN  
3908           NaN  
3909           NaN  

[3910 rows x 39 columns]

In [127]:
df2.to_csv('save2.csv')
df.to_csv('save1.csv')

In [157]:

for index, row in df2.iterrows():
#     print(row['customerID'])
        temp =  df.loc[df.customerID == row['customerID']]
        temp2 = temp.to_numpy()[0][1:]
        row[2:] = temp2
df2

customerID      result Fast Food Cakes & Bakery Western  \
0             1   Fast Food      10.0            2.0     1.0   
1             1   Fast Food      10.0            2.0     1.0   
2             1   Fast Food      10.0            2.0     1.0   
3             1   Fast Food      10.0            2.0     1.0   
4             1   Fast Food      10.0            2.0     1.0   
...         ...         ...       ...            ...     ...   
3905        100      Indian       5.0            NaN     NaN   
3906        100      Indian       5.0            NaN     NaN   
3907        100  Sandwiches       5.0            NaN     NaN   
3908        100  Sandwiches       5.0            NaN     NaN   
3909        100     Burgers       5.0            NaN     NaN   

     Non-alcoholic Drinks Chinese Pizza Thai Indian  ... French Seafood  \
0                     1.0     4.0   5.0  1.0    1.0  ...    NaN     NaN   
1                     1.0     4.0   5.0  1.0    1.0  ...    NaN     NaN   
2                     1.0     4.0   5.0  1.0    1.0  ...    NaN     NaN   
3                     1.0     4.0   5.0  1.0    1.0  ...    NaN     NaN   
4                     1.0     4.0   5.0  1.0    1.0  ...    NaN     NaN   
...                   ...     ...   ...  ...    ...  ...    ...     ...   
3905                  NaN    18.0   NaN  NaN    3.0  ...    NaN     NaN   
3906                  NaN    18.0   NaN  NaN    3.0  ...    NaN     NaN   
3907                  NaN    18.0   NaN  NaN    3.0  ...    NaN     NaN   
3908                  NaN    18.0   NaN  NaN    3.0  ...    NaN     NaN   
3909                  NaN    18.0   NaN  NaN    3.0  ...    NaN     NaN   

     Middle Eastern Malay Vegetarian Filipino Turkish German Sushi  \
0               NaN   NaN        NaN      NaN     NaN    NaN   NaN   
1               NaN   NaN        NaN      NaN     NaN    NaN   NaN   
2               NaN   NaN        NaN      NaN     NaN    NaN   NaN   
3               NaN   NaN        NaN      NaN     NaN    NaN   NaN   
4               NaN   NaN        NaN      NaN     NaN    NaN   NaN   
...             ...   ...        ...      ...     ...    ...   ...   
3905            NaN   NaN        NaN      NaN     NaN    NaN   NaN   
3906            NaN   NaN        NaN      NaN     NaN    NaN   NaN   
3907            NaN   NaN        NaN      NaN     NaN    NaN   NaN   
3908            NaN   NaN        NaN      NaN     NaN    NaN   NaN   
3909            NaN   NaN        NaN      NaN     NaN    NaN   NaN   

     Mediterranean  
0              NaN  
1              NaN  
2              NaN  
3              NaN  
4              NaN  
...            ...  
3905           NaN  
3906           NaN  
3907           NaN  
3908           NaN  
3909           NaN  

[3910 rows x 39 columns]

In [175]:
df2 = df2.fillna(0)
df = df.fillna(0)
df2.to_csv('save2.csv')
df.to_csv('save1.csv')

In [177]:
X = df2.iloc[:, 2:].values
y = df2.iloc[:, 1].values

In [178]:
X

array([[10.,  2.,  1., ...,  0.,  0.,  0.],
       [10.,  2.,  1., ...,  0.,  0.,  0.],
       [10.,  2.,  1., ...,  0.,  0.,  0.],
       ...,
       [ 5.,  0.,  0., ...,  0.,  0.,  0.],
       [ 5.,  0.,  0., ...,  0.,  0.,  0.],
       [ 5.,  0.,  0., ...,  0.,  0.,  0.]])

In [179]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [180]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
KNN below:

In [181]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [182]:
y_pred = classifier.predict(X_test)

In [211]:
temp = df.drop('customerID', 1)
y_pred = classifier.predict(temp)
print(y_pred)
np.savetxt("KNN result.csv", y_pred, fmt='%s')

['Chinese' 'Chinese' 'Burgers' 'Non-alcoholic Drinks' 'Singaporean'
 'Chinese' 'Chinese' 'Chinese' 'Burgers' 'Singaporean' 'Chinese' 'Chinese'
 'Fast Food' 'Chinese' 'American' 'Indian' 'Western' 'Chinese' 'Chinese'
 'Chinese' 'Fast Food' 'Chinese' 'Singaporean' 'Chinese' 'Burgers'
 'Filipino' 'Indian' 'Chinese' 'Chinese' 'Chinese' 'Singaporean'
 'Singaporean' 'Singaporean' 'Chinese' 'Chinese' 'American' 'Indian'
 'Asian' 'Fast Food' 'Chinese' 'Chinese' 'Indian' 'Indian' 'Chicken'
 'Asian' 'Chinese' 'Indian' 'Italian' 'Japanese' 'Chinese'
 'Cakes & Bakery' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Singaporean'
 'Singaporean' 'Chicken' 'Indian' 'Thai' 'Indian' 'Chinese' 'Chinese'
 'Chinese' 'Chinese' 'Western' 'Chinese' 'Singaporean' 'Japanese'
 'Chinese' 'Chinese' 'International' 'Healthy Food' 'Japanese' 'Chinese'
 'Chinese' 'Chinese' 'Asian' 'Chinese' 'Chinese' 'Chinese' 'Chinese'
 'Asian' 'Fast Food' 'Chinese' 'Chinese' 'Burgers' 'Chinese' 'Chinese'
 'American' 'Chinese' 'Chinese' 'W

/var/folders/g5/k18zz6b532x92bqmxpqqld100000gp/T/ipykernel_19410/580263878.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  temp = df.drop('customerID', 1)


In [183]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[1 0 0 ... 0 0 0]
 [1 8 0 ... 0 0 0]
 [0 3 5 ... 0 0 1]
 ...
 [0 1 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 [3 0 1 ... 0 0 3]]
                      precision    recall  f1-score   support

            American       0.04      0.05      0.05        20
               Asian       0.12      0.36      0.18        22
             Burgers       0.18      0.23      0.20        22
      Cakes & Bakery       0.06      0.17      0.08         6
             Chicken       0.00      0.00      0.00        12
             Chinese       0.46      0.72      0.56       182
            Desserts       0.50      0.13      0.21        15
            European       0.00      0.00      0.00         2
           Fast Food       0.25      0.36      0.30        61
            Filipino       1.00      0.83      0.91        12
               Halal       0.00      0.00      0.00         8
        Healthy Food       0.00      0.00      0.00        19
              Indian       0.33      0.28      0.30        53
          I

/Users/wuzhong/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/wuzhong/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/wuzhong/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
Decision tree below

In [188]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [189]:
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [190]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.35038363171355497


In [210]:
temp = df.drop('customerID', 1)
y_pred = clf.predict(temp)
print(y_pred)
np.savetxt("decision tree result.csv", y_pred, fmt='%s')

['Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese'
 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese'
 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese'
 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese'
 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese'
 'Chinese' 'Chinese' 'Chinese' 'Singaporean' 'Chinese' 'Chinese' 'Chinese'
 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese'
 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese'
 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese'
 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese'
 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese'
 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese'
 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese'
 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese' 'Chinese'
 '

/var/folders/g5/k18zz6b532x92bqmxpqqld100000gp/T/ipykernel_19410/3780430789.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  temp = df.drop('customerID', 1)


[[10.  2.  1. ...  0.  0.  0.]
 [10.  2.  1. ...  0.  0.  0.]
 [10.  2.  1. ...  0.  0.  0.]
 ...
 [ 5.  0.  0. ...  0.  0.  0.]
 [ 5.  0.  0. ...  0.  0.  0.]
 [ 5.  0.  0. ...  0.  0.  0.]]


ModuleNotFoundError: No module named 'sklearn.externals.six'